repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: mentoring

  # A short description of the repository that will show up on GitHub
  description: ğŸ‘©ğŸ¿â€ğŸ“ğŸ‘¨ğŸ½â€ğŸ“ğŸ‘©ğŸ»â€ğŸ“CNCF Mentoring + CommunityBridge + Summer of Code

  # A URL with more information about the repository
  homepage: https://mentoring.cncf.io

  # Collaborators: give specific users access to this repository.
collaborators:
  # CNCF repo admins
  - username: caniszczyk
    permission: admin

  - username: idvoretskyi
    permission: admin
    
  - username: amye
    permission: admin

  - username: nate-double-u
    permission: admin
    
  - username: jeefy
    permission: admin

  - username: thisisobate
    permission: maintain

  # CNCF TAG Contributor Strategy & Mentoring WG chairs, leads
  - username: jaytiaki
    permission: maintain

  - username: geekygirldawn
    permission: maintain

  - username: jberkus
    permission: maintain

  - username: CathPag
    permission: maintain

  - username: carolynvs
    permission: maintain
   
  - username: riaankl
    permission: maintain

labels:
  - name: lfx mentorship
    color: a2dcf2
  - name: enhancement
    color: 84b6eb
  - name: help-wanted
    color: ffff54
  - name: good first issue
    color: ff8c00
  - name: hold
    color: d93f0b
  - name: time-sensitive
    description: issues or PRs that have a due date
    color: b60205
  - name: getting started
    color: 3B8924
  - name: outreachy
    color: 7fd811
  - name: season of docs
    color: f4af97
  - name: summer of code
    color: 00ffff
  - name: season of docs
    color: 00ff80
  - name: spring
    color: 1ED626
  - name: "Term 1: March-May"
    color: 1ED626
  - name: summer
    color: FBCA04
  - name: "Term 3: Sept-Nov"
    color: FBCA04
  - name: fall
    color: C5DEF5
  - name: '2022'
    color: 0052CC
  - name: '2023'
    color: 0052CC
  # project labels
  - name: Argo
  - name: Brigade
  - name: Buildpacks
  - name: cert-manager
  - name: "Chaos Mesh"
  - name: CoreDNS
  - name: in-toto
  - name: Karmada
  - name: Keylime
  - name: Knative
  - name: KubeArmor
  - name: KubeEdge
  - name: Kubernetes
  - name: KubeVela
  - name: Kyverno
  - name: LitmusChaos
  - name: Meshery
  - name: Pixie
  - name: "Service Mesh Performance"
  - name: Thanos
  - name: "The Update Framework"
  - name: TiKV
  - name: Vitess
  - name: WasmEdge
  # one "blank" line
  - name: blank

